<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BiodatasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('biodatas')->insert([
            [
                'nama_lengkap'=>'Rakha',
                'jenis_kelamin'=>'L',
                'tanggal_lahir'=>'2009-03-23',
                'tempat_lahir'=>'Bandung',
                'agama'=>'Islam',
                'alamat'=>'Bandung',
                'telepon'=>"089690589",
                'email'=>'rakha@gmail.com',
                'cover'=>'.',
            ],
            [
                'nama_lengkap'=>'Jihad',
                'jenis_kelamin'=>'L',
                'tanggal_lahir'=>'2009-03-23',
                'tempat_lahir'=>'Bandung',
                'agama'=>'Islam',
                'alamat'=>'Bandung',
                'telepon'=>"089690589",
                'email'=>'jihad@gmail.com',
                'cover'=>'.',
            ],
            [
                'nama_lengkap'=>'Davin',
                'jenis_kelamin'=>'L',
                'tanggal_lahir'=>'2009-03-23',
                'tempat_lahir'=>'Bandung',
                'agama'=>'Islam',
                'alamat'=>'Bandung',
                'telepon'=>"089690589",
                'email'=>'davin@gmail.com',
                'cover'=>'.',
            ],
            [
                'nama_lengkap'=>'Fakhri',
                'jenis_kelamin'=>'L',
                'tanggal_lahir'=>'2009-03-23',
                'tempat_lahir'=>'Bandung',
                'agama'=>'Islam',
                'alamat'=>'Bandung',
                'telepon'=>"089690589",
                'email'=>'fakhri@gmail.com',
                'cover'=>'.',
            ],
            [
                'nama_lengkap'=>'jauf',
                'jenis_kelamin'=>'L',
                'tanggal_lahir'=>'2009-03-23',
                'tempat_lahir'=>'Bandung',
                'agama'=>'Islam',
                'alamat'=>'Bandung',
                'telepon'=>"089690589",
                'email'=>'jauf@gmail.com',
                'cover'=>'.',
            ],
            [
                'nama_lengkap'=>'rehan',
                'jenis_kelamin'=>'L',
                'tanggal_lahir'=>'2009-03-23',
                'tempat_lahir'=>'Bandung',
                'agama'=>'Islam',
                'alamat'=>'Bandung',
                'telepon'=>"089690589",
                'email'=>'rehan@gmail.com',
                'cover'=>'.',
            ],
            [
                'nama_lengkap'=>'teguh',
                'jenis_kelamin'=>'L',
                'tanggal_lahir'=>'2009-03-23',
                'tempat_lahir'=>'Bandung',
                'agama'=>'Islam',
                'alamat'=>'Bandung',
                'telepon'=>"089690589",
                'email'=>'teguh@gmail.com',
                'cover'=>'.',
            ],
            [
                'nama_lengkap'=>'bara',
                'jenis_kelamin'=>'L',
                'tanggal_lahir'=>'2009-03-23',
                'tempat_lahir'=>'Bandung',
                'agama'=>'Islam',
                'alamat'=>'Bandung',
                'telepon'=>"089690589",
                'email'=>'bara@gmail.com',
                'cover'=>'.',
            ],
            [
                'nama_lengkap'=>'fadil',
                'jenis_kelamin'=>'L',
                'tanggal_lahir'=>'2009-03-23',
                'tempat_lahir'=>'Bandung',
                'agama'=>'Islam',
                'alamat'=>'Bandung',
                'telepon'=>"089690589",
                'email'=>'fadil@gmail.com',
                'cover'=>'.',
            ],
            [
                'nama_lengkap'=>'radit',
                'jenis_kelamin'=>'L',
                'tanggal_lahir'=>'2009-03-23',
                'tempat_lahir'=>'Bandung',
                'agama'=>'Islam',
                'alamat'=>'Bandung',
                'telepon'=>"089690589",
                'email'=>'radit@gmail.com',
                'cover'=>'.',
            ]
        ]);
    }
}
